// Code generated by Kitex v0.13.1. DO NOT EDIT.
package biobankservice

import (
	server "github.com/cloudwego/kitex/server"
	biobank "github.com/yxrxy/AllergyBase/kitex_gen/biobank"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler biobank.BiobankService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler biobank.BiobankService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
