// Code generated by Kitex v0.13.1. DO NOT EDIT.
package clinicalservice

import (
	server "github.com/cloudwego/kitex/server"
	clinical "github.com/yxrxy/AllergyBase/kitex_gen/clinical"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler clinical.ClinicalService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler clinical.ClinicalService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
